/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 animate.glb
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
 const Animate = (props) => {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/animate.glb')
  const { actions, names } = useAnimations(animations, group)
  console.log(names)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh name="BaseMesh_Female" geometry={nodes.BaseMesh_Female.geometry} material={nodes.BaseMesh_Female.material} skeleton={nodes.BaseMesh_Female.skeleton} />
        </group>
      </group>
    </group>
  )
}

export default Animate
useGLTF.preload('/animate.glb')
