/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 clot.glb
*/

import React, {useEffect, useRef} from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

const Model = (props) => {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/clot.glb')
  const { actions } = useAnimations(animations, group)
  useEffect(() => {
    actions['Armature|mixamo.com|Layer0'].play()
  })
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh name="BaseMesh_Female001" geometry={nodes.BaseMesh_Female001.geometry} material={nodes.BaseMesh_Female001.material} skeleton={nodes.BaseMesh_Female001.skeleton} />
          {
            props.isWrist && <skinnedMesh name="gloves" geometry={nodes.gloves.geometry} material={materials.f} skeleton={nodes.gloves.skeleton} />
          }
          {
            props.isBolka && <skinnedMesh name="Mesh001" geometry={nodes.Mesh001.geometry} material={materials['Material.002']} skeleton={nodes.Mesh001.skeleton} />
          }
          {
            props.isLeggins && <skinnedMesh name="Mesh" geometry={nodes.Mesh.geometry} material={materials['Material.001']} skeleton={nodes.Mesh.skeleton} />
          }



        </group>
      </group>
    </group>
  )
}

export default Model

useGLTF.preload('/clot.glb')
