/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 glowers.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/glowers.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.glow.geometry} material={materials.Material4} />
    </group>
  )
}

useGLTF.preload('/glowers.glb')
