/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 personA.gltf
*/

import React, { useRef } from 'react'
import {useAnimations, useGLTF} from '@react-three/drei'
import Person from "./Person";

const PersonA = (props) => {
    const group = useRef()
    const { nodes, materials, animations } = useGLTF('person.gltf')
    const {actions, names} = useAnimations(animations, group)
    console.log(names)
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.BaseMesh_Female.geometry} material={nodes.BaseMesh_Female.material} />
    </group>
  )
}
export default PersonA

useGLTF.preload('/personA.gltf')
