/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 person.gltf
*/

import React, { useRef } from 'react'
import {useAnimations, useGLTF} from '@react-three/drei'

const Person = (props) => {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('person.gltf')
    const {actions, names} = useAnimations(animations, group)
  console.log(names)
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.BaseMesh_Female.geometry} material={nodes.BaseMesh_Female.material} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
    </group>
  )
}

export default Person

useGLTF.preload('/person.gltf')
